---
abstract: 'Redis support for IO::Async'
author:
  - 'Tom Molesworth <TEAM@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::Deep: '0'
  Test::Fatal: '0.016'
  Test::HexString: '0'
  Test::MockModule: '0'
  Test::More: '0.98'
  Variable::Disposition: '0.004'
configure_requires:
  ExtUtils::MakeMaker: '0'
  File::ShareDir::Install: '0.06'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-Async-Redis
no_index:
  directory:
    - eg
    - share
    - shares
    - t
    - xt
provides:
  Net::Async::Redis:
    file: lib/Net/Async/Redis.pm
    version: '4.000'
  Net::Async::Redis::Cluster:
    file: lib/Net/Async/Redis/Cluster.pm
    version: '4.000'
  Net::Async::Redis::Cluster::Node:
    file: lib/Net/Async/Redis/Cluster/Node.pm
    version: '4.000'
  Net::Async::Redis::Commands:
    file: lib/Net/Async/Redis/Commands.pm
    version: '4.000'
  Net::Async::Redis::Multi:
    file: lib/Net/Async/Redis/Multi.pm
    version: '4.000'
  Net::Async::Redis::Protocol:
    file: lib/Net/Async/Redis/Protocol.pm
    version: '4.000'
  Net::Async::Redis::Server:
    file: lib/Net/Async/Redis/Server.pm
    version: '4.000'
  Net::Async::Redis::Server::Connection:
    file: lib/Net/Async/Redis/Server/Connection.pm
    version: '4.000'
  Net::Async::Redis::Server::Database:
    file: lib/Net/Async/Redis/Server/Database.pm
    version: '4.000'
  Net::Async::Redis::Subscription:
    file: lib/Net/Async/Redis/Subscription.pm
    version: '4.000'
  Net::Async::Redis::Subscription::Message:
    file: lib/Net/Async/Redis/Subscription/Message.pm
    version: '4.000'
requires:
  Cache::LRU: '0.04'
  Class::Method::Modifiers: '0'
  Digest::CRC: '0.22'
  Dir::Self: '0'
  File::ShareDir: '0'
  File::ShareDir::Install: '0'
  Future: '0.47'
  Future::AsyncAwait: '0.48'
  IO::Async: '0'
  List::BinarySearch::XS: '0.09'
  List::Util: '1.55'
  Log::Any: '1.708'
  Math::Random::Secure: '0'
  Metrics::Any: '0'
  OpenTracing::Any: '1.003'
  Path::Tiny: '0'
  Ryu: '2.009'
  Ryu::Async: '0.019'
  Syntax::Keyword::Dynamically: '0.07'
  Syntax::Keyword::Match: '0'
  Syntax::Keyword::Try: '0.21'
  URI: '0'
  URI::redis: '0'
  YAML::XS: '0.88'
  curry: '0'
  parent: '0'
resources:
  bugtracker: https://github.com/team-at-cpan/Net-Async-Redis/issues
  homepage: https://github.com/team-at-cpan/Net-Async-Redis
  repository: https://github.com/team-at-cpan/Net-Async-Redis.git
version: '4.000'
x_authority: cpan:TEAM
x_contributors:
  - 'Eyad Arnabeh <eyadof@gmail.com>'
  - 'Paul "LeoNerd" Evans <leonerd@leonerd.org.uk>'
  - 'tm604 <tom@perlsite.co.uk>'
  - 'Marc Frank <mfrank@sipxpert.de>'
  - 'Michael Mueller <michael.mueller@binary.com>'
  - 'Mohammad S Anwar <mohammad.anwar@yahoo.com>'
  - 'shaydo-deriv <129739908+shaydo-deriv@users.noreply.github.com>'
x_generated_by_perl: v5.36.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: 'Artistic-1.0-Perl OR GPL-1.0-or-later'
